export const galleryImageList = [
  { id: 1, src: "/1.png", path: 1, alt: "image" },
  { id: 2, src: "/2.png", path: 2, alt: "image" },
  { id: 3, src: "/3.png", path: 3, alt: "image" },
  { id: 4, src: "/4.png", path: 4, alt: "image" },
  { id: 5, src: "/5.png", path: 5, alt: "image" },
  { id: 6, src: "/6.png", path: 6, alt: "image" },
  { id: 7, src: "/7.png", path: 7, alt: "image" },
  { id: 8, src: "/8.png", path: 8, alt: "image" },
  { id: 9, src: "/9.png", path: 9, alt: "image" },
  { id: 10, src: "/10.png", path: 10, alt: "image" },
  { id: 11, src: "/11.png", path: 11, alt: "image" },
  { id: 12, src: "/12.png", path: 12, alt: "image" },
  { id: 13, src: "/13.png", path: 13, alt: "image" },
];
